# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - label: "${TPU_VERSION:-tpu6e} Unit tests for openai/gpt-oss-120b"
    key: "${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_UnitTest"
    agents:
      queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
    soft_fail: true
    # The strict-match is failing due to pattern mismatch, see #2318 for details.
    # TODO(#2318): set proper strict-match threshold.
    commands:
      - |
        if [ "${TPU_VERSION:-tpu6e}" = "tpu6e" ]; then
          buildkite-agent meta-data set "${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_UnitTest" "not enough HBM"
        else
          .buildkite/scripts/run_in_docker.sh \
            bash /workspace/tpu_inference/tests/e2e/check_lm_eval.sh  --model_name "openai/gpt-oss-120b" --use_moe_ep_kernel 1 --tensor_parallel_size 8 --max_model_len 2048 --max_num_batched_tokens 2048 --max_gen_toks 256 --enable_expert_parallel 1 --flex_threshold 0.50 --strict_threshold 0.0
        fi
  - label: "${TPU_VERSION:-tpu6e} Record unit test result for openai/gpt-oss-120b"
    key: "${TPU_VERSION:-tpu6e}_record_openai_gpt-oss-120b_UnitTest"
    depends_on: "${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_UnitTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "openai/gpt-oss-120b"
      CI_STAGE: "UnitTest"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_UnitTest

  - label: "${TPU_VERSION:-tpu6e} Accuracy for openai/gpt-oss-120b"
    key: "${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_Accuracy"
    depends_on: "${TPU_VERSION:-tpu6e}_record_openai_gpt-oss-120b_UnitTest"
    agents:
      queue: cpu  # TODO: replace with execution environment
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_Accuracy" "unverified"
  - label: "${TPU_VERSION:-tpu6e} Record accuracy result for openai/gpt-oss-120b"
    key: "${TPU_VERSION:-tpu6e}_record_openai_gpt-oss-120b_Accuracy"
    depends_on: "${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_UnitTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "openai/gpt-oss-120b"
      CI_STAGE: "Accuracy/Correctness"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_UnitTest

  - label: "${TPU_VERSION:-tpu6e} Performance benchmarks for openai/gpt-oss-120b"
    key: "${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_Benchmark"
    depends_on: "${TPU_VERSION:-tpu6e}_record_openai_gpt-oss-120b_Accuracy"
    agents:
      queue: cpu  # TODO: replace with execution environment
    soft_fail: true
    commands:
      - |
        buildkite-agent meta-data set "${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_Benchmark" "unverified"
  - label: "${TPU_VERSION:-tpu6e} Record performance benchmark result for openai/gpt-oss-120b"
    key: "${TPU_VERSION:-tpu6e}_record_openai_gpt-oss-120b_Benchmark"
    depends_on: "${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_Benchmark"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "openai/gpt-oss-120b"
      CI_STAGE: "Benchmark"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_openai_gpt-oss-120b_Benchmark
